name: CI/CD pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: voxform

jobs:
  # test:
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.12'

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Run pytest
  #       run: pytest -q

  # ==================================================
  # JOB 1 — Build & Push App's DOcker Image
  # ==================================================

  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push VoxForm image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest


  # ==================================================
  # JOB 2 — Deploy to EC2
  # ==================================================

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            set -e

            echo "======================================"
            echo "Starting VoxForm deployment"
            echo "======================================"

            AWS_REGION="ap-south-1"
            ECR_REGISTRY="131708657836.dkr.ecr.ap-south-1.amazonaws.com"
            ECR_REPOSITORY="voxform"
            IMAGE_TAG="${{ github.sha }}"

            echo "Logging into ECR..."

            aws ecr get-login-password \
              --region $AWS_REGION \
              | docker login \
                  --username AWS \
                  --password-stdin \
                  $ECR_REGISTRY

            echo "Pulling image..."

            docker pull \
              $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            echo "Stopping existing container..."

            docker stop voxform || true

            echo "Removing existing container..."

            docker rm voxform || true

            echo "Starting new container..."

            docker run -d \
              --name voxform \
              --restart always \
              --env-file /home/ubuntu/voxform/.env.production \
              -p 8000:8000 \
              $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            echo "Cleaning unused images..."

            docker image prune -af

            echo "======================================"
            echo "Deployment completed"
            echo "======================================"

            docker ps

# -------------------------------------------------------------------------------
# -------------------------------------------------------------------------------

# Required GitHub secrets & variables:
# AWS_REGION - ap-south-1
# ECR_REPOSITORY - voxform
# AWS_ROLE_ARN - GitHub OIDC enabled Role for ECR Push

# Notes:
# - This workflow runs on merge / push to main and later on will validate the tests first.
# - The build and pushes Docker image to AWS Elastic Container Registry.
# - The VM deploy job runs to restart new docker image from ECR.
